<!-- Data generated by EDINA Digimap, University of Edinburgh for bri:3fdf9738967ff700 on 2018-11-27 11:44:21.533. --><!--Created by GO Publisher WFS 3.0.0.5 Build 734cfe0 from 2014-02-26 11:40--><!--Snowflake Software Ltd. (http://www.snowflakesoftware.com)--><osgb:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:osgb="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb http://www.ordnancesurvey.co.uk/xml/schema/v6/OSDNFFeatures.xsd">
  <gml:boundedBy>
    <gml:null>unknown</gml:null>
  </gml:boundedBy>
  <osgb:queryTime>2018-11-27T11:44:22</osgb:queryTime>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021652551">
      <osgb:version>3</osgb:version>
      <osgb:versionDate>2005-09-19</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Private Road - Restricted Access</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>156.47</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356634.0,172993.0 356632.0,172981.0 356627.0,172951.0 356619.0,172895.0 356619.0,172889.0 356623.0,172864.0 356626.0,172856.0 356633.0,172840.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567400" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567386" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279381781"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382771"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021688040">
      <osgb:version>3</osgb:version>
      <osgb:versionDate>2005-09-16</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Local Street</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>83.19</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356658.0,172939.0 356715.0,172966.0 356733.0,172975.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567389" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567401" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382773"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382779"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382201"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021688041">
      <osgb:version>4</osgb:version>
      <osgb:versionDate>2005-09-16</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Local Street</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>133.26</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356677.0,173109.0 356664.0,173102.0 356654.0,173093.0 356648.0,173088.0 356646.0,173086.0 356644.0,173082.0 356642.0,173075.0 356641.844,173070.0 356641.0,173043.0 356640.0,173024.0 356636.0,173000.0 356634.0,172993.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567403" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567400" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396077"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382771"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002084893340"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021688042">
      <osgb:version>3</osgb:version>
      <osgb:versionDate>2005-09-16</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Local Street</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>56</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356658.0,172939.0 356672.0,172905.0 356675.0,172899.0 356681.0,172888.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567389" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567388" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382183"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382192"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382201"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021688044">
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2005-09-15</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Dual Carriageway</osgb:natureOfRoad>
      <osgb:length>115.72</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356379.0,173301.0 356389.0,173286.0 356396.0,173277.0 356416.0,173257.0 356424.0,173250.0 356458.0,173217.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567408" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567395" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002317270996"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396259"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021688065">
      <osgb:version>4</osgb:version>
      <osgb:versionDate>2006-01-25</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Local Street</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>112.11</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356681.0,172888.0 356695.0,172868.0 356705.0,172856.0 356717.0,172848.0 356722.0,172844.0 356750.0,172829.3 356762.0,172823.0 356768.0,172822.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567388" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567433" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002084893339"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382181"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382183"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021730444">
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2005-10-06</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Dual Carriageway</osgb:natureOfRoad>
      <osgb:length>104.83</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356391.597,173297.749 356404.0,173283.0 356423.0,173261.0 356434.0,173250.0 356440.0,173244.0 356458.0,173217.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567390" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567395" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396259"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021730447">
      <osgb:version>4</osgb:version>
      <osgb:versionDate>2006-02-03</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>32.75</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356599.0,173151.0 356600.0,173151.625 356607.0,173156.0 356627.0,173168.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567398" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567399" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279395895"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396528"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396555"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396612"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021730456">
      <osgb:version>6</osgb:version>
      <osgb:versionDate>2005-09-15</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Dual Carriageway</osgb:natureOfRoad>
      <osgb:length>21.9</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356377.0,173314.0 356386.854,173304.234 356391.597,173297.749</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567409" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567390" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002317270996"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396259"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021632406">
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2007-08-10</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Local Street</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>310.73</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356230.0,172945.0 356230.0,172947.0 356238.0,172962.0 356250.0,172983.0 356262.0,173000.0 356267.0,173011.0 356269.0,173018.0 356270.0,173021.0 356270.0,173027.0 356267.0,173040.0 356263.0,173047.0 356255.0,173054.0 356251.0,173056.0 356247.0,173058.0 356239.0,173060.0 356230.0,173060.0 356229.0,173060.0 356223.0,173060.0 356186.0,173049.0 356131.0,173035.0 356091.0,173028.0 356074.0,173027.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567380" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567372" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279384626"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279384711"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279397396"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021730452">
      <osgb:version>4</osgb:version>
      <osgb:versionDate>2009-04-26</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Local Street</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>59.09</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356634.0,172993.0 356651.739,172953.624 356658.0,172939.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567400" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567389" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279381780"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382201"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382771"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021652547">
      <osgb:version>7</osgb:version>
      <osgb:versionDate>2009-08-28</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>131.37</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356458.0,173217.0 356473.0,173201.0 356493.0,173173.0 356500.0,173161.0 356505.012,173151.41 356515.0,173132.0 356515.33,173131.22 356521.0,173116.0 356524.0,173105.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567395" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567394" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396259"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396525"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021621264">
      <osgb:version>6</osgb:version>
      <osgb:versionDate>2012-03-28</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>711.23</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356587.0,173928.0 356579.0,173918.0 356570.0,173913.0 356548.0,173907.0 356542.408,173905.679 356537.0,173903.0 356533.0,173901.0 356528.0,173897.0 356518.0,173887.0 356510.0,173875.0 356500.0,173859.0 356492.0,173847.0 356487.0,173841.0 356480.0,173834.0 356470.0,173826.0 356433.053,173800.0 356416.0,173788.0 356398.0,173772.0 356393.0,173765.0 356390.0,173760.0 356389.0,173757.0 356387.0,173747.0 356387.0,173734.0 356389.0,173724.0 356395.0,173697.0 356397.0,173687.0 356400.0,173668.0 356401.0,173655.0 356401.0,173645.0 356400.0,173627.0 356400.0,173615.0 356396.0,173594.0 356395.0,173587.0 356392.0,173576.0 356387.0,173563.0 356378.0,173542.0 356364.0,173517.0 356358.0,173500.0 356348.0,173467.0 356347.0,173459.0 356346.0,173455.0 356346.0,173440.0 356348.0,173426.0 356351.0,173413.0 356354.805,173400.0 356363.0,173372.0 356375.499,173344.062 356380.0,173334.0 356381.0,173332.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567693" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567410" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002084893429"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279390799"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002317270996"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021688045">
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2012-03-28</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Traffic Island Link At Junction</osgb:natureOfRoad>
      <osgb:length>35.86</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356381.0,173332.0 356384.441,173320.551 356387.628,173309.946 356390.726,173301.137 356391.597,173297.749</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567410" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567390" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002317270996"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396259"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021730448">
      <osgb:version>4</osgb:version>
      <osgb:versionDate>2012-04-01</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Dual Carriageway</osgb:natureOfRoad>
      <osgb:length>48.75</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356627.0,173168.0 356632.0,173168.0 356634.0,173168.0 356638.114,173170.618 356645.0,173175.0 356651.0,173180.0 356655.324,173181.73 356656.0,173182.0 356671.0,173186.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567399" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567396" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279395902"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396411"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396612"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396637"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021730449">
      <osgb:version>4</osgb:version>
      <osgb:versionDate>2012-04-01</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Dual Carriageway</osgb:natureOfRoad>
      <osgb:length>51.46</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356671.0,173186.0 356662.0,173188.0 356659.0,173188.0 356655.0,173188.0 356654.162,173187.581 356651.0,173186.0 356642.0,173181.0 356632.0,173175.0 356628.0,173171.0 356627.0,173168.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567396" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567399" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279395902"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396411"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396612"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021761951">
      <osgb:version>6</osgb:version>
      <osgb:versionDate>2012-03-28</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Dual Carriageway</osgb:natureOfRoad>
      <osgb:length>45.01</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356359.555,173341.02 356361.201,173332.695 356364.139,173326.875 356371.365,173312.56 356376.0,173304.0 356379.0,173301.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567407" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567408" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002317270996"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279391645"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021761952">
      <osgb:version>6</osgb:version>
      <osgb:versionDate>2012-03-28</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Traffic Island Link At Junction</osgb:natureOfRoad>
      <osgb:length>18.56</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356381.0,173332.0 356379.222,173326.073 356378.0,173322.0 356377.531,173320.122 356377.0,173318.0 356376.98,173315.076 356377.0,173314.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567410" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567409" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002317270996"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021779237">
      <osgb:version>6</osgb:version>
      <osgb:versionDate>2012-03-28</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Slip Road</osgb:natureOfRoad>
      <osgb:length>13.15</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356377.0,173314.0 356377.667,173309.667 356379.0,173301.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567409" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567408" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002317270996"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021779238">
      <osgb:version>6</osgb:version>
      <osgb:versionDate>2012-03-28</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Dual Carriageway</osgb:natureOfRoad>
      <osgb:length>32.53</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356359.555,173341.02 356366.622,173334.244 356367.104,173333.304 356377.0,173314.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567407" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567409" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000002317270996"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279391645"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000022086579">
      <osgb:version>2</osgb:version>
      <osgb:versionDate>2012-03-28</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>708.07</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356265.0,174029.0 356272.0,174009.0 356275.0,174000.0 356328.0,173818.0 356332.776,173800.0 356341.0,173769.0 356344.0,173755.0 356345.0,173743.0 356347.0,173730.0 356350.0,173694.0 356350.0,173675.0 356350.0,173648.0 356348.0,173618.0 356346.0,173586.0 356341.0,173561.0 356338.239,173548.971 356327.0,173500.0 356324.0,173485.0 356324.0,173482.0 356324.0,173472.0 356324.0,173459.0 356326.0,173446.0 356331.0,173417.0 356335.0,173403.0 356335.889,173400.0 356343.0,173376.0 356359.555,173341.02</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000022086523" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567407" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279391645"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021730445">
      <osgb:version>6</osgb:version>
      <osgb:versionDate>2014-03-05</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>56.08</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356524.0,173105.0 356560.312,173127.077 356561.888,173127.93 356569.828,173132.696 356572.0,173134.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567394" gradeSeparation="1" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567397" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396620"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396525"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021730453">
      <osgb:version>4</osgb:version>
      <osgb:versionDate>2015-04-09</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Local Street</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>44.77</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356681.0,172888.0 356722.0,172906.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567388" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567387" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382181"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382183"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279382084"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb5000005198335433">
      <osgb:version>1</osgb:version>
      <osgb:versionDate>2017-02-02</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>Alley</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>134.62</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356288.704,172778.755 356287.129,172784.19 356287.011,172789.736 356287.139,172794.345 356287.365,172797.053 356288.427,172803.307 356289.052,172806.058 356290.079,172809.798 356291.849,172814.872 356293.383,172820.182 356294.056,172822.816 356294.917,172827.145 356295.389,172829.505 356296.215,172834.697 356296.569,172839.772 356296.215,172847.324 356295.979,172853.343 356295.625,172859.361 356295.389,172864.2 356295.153,172869.038 356295.153,172877.062 356295.239,172880.123 356295.625,172885.913 356296.687,172892.64 356297.631,172899.012 356299.166,172903.732 356300.228,172904.558 356304.712,172909.279</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb5000005198335361" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb5000005198335360" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb9999"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021761946">
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2017-01-19</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Traffic Island Link</osgb:natureOfRoad>
      <osgb:length>32.12</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356344.0,172995.0 356348.0,172995.0 356351.0,172995.0 356354.243,172996.802 356360.0,173000.0 356363.496,173002.185 356368.0,173005.0 356369.0,173007.0 356370.0,173010.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567393" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567391" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279397345"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279384644"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279384643"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005124913028"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021761947">
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2017-02-12</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Traffic Island Link</osgb:natureOfRoad>
      <osgb:length>33.55</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356572.0,173134.0 356575.0,173134.0 356579.0,173134.0 356582.745,173135.872 356583.0,173136.0 356589.0,173140.0 356591.609,173142.609 356593.0,173144.0 356599.0,173151.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567397" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567398" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005124913031"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396620"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279395895"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021761945">
      <osgb:version>6</osgb:version>
      <osgb:versionDate>2017-01-19</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Traffic Island Link</osgb:natureOfRoad>
      <osgb:length>31.75</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356344.0,172995.0 356350.0,173001.8 356351.115,173002.829 356353.9,173005.4 356358.325,173007.962 356359.6,173008.7 356359.794,173008.777 356364.4,173010.6 356370.0,173010.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567393" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567391" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005124913028"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279397385"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279397345"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279397250"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279384643"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb5000005200001396">
      <osgb:version>2</osgb:version>
      <osgb:versionDate>2017-03-02</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>39.91</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356267.252,172930.842 356268.304,172933.475 356270.412,172938.002 356272.352,172941.622 356274.5,172945.119 356276.55,172947.95 356278.249,172949.971 356280.06,172951.892 356283.951,172955.468 356286.287,172957.369 356288.398,172958.958 356291.79,172961.363</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb5000005200001356" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb5000005200001357" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005200001350"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005200001351"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005200001352"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021761948">
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2017-03-30</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Traffic Island Link</osgb:natureOfRoad>
      <osgb:length>33.1</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356599.0,173151.0 356588.354,173148.097 356588.0,173148.0 356581.0,173144.0 356578.998,173142.332 356575.0,173139.0 356572.0,173134.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567398" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567397" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279395895"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396620"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005124913036"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021761943">
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2017-03-02</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Dual Carriageway</osgb:natureOfRoad>
      <osgb:length>30.24</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356316.809,172976.957 356310.0,172971.0 356309.864,172970.9 356298.741,172962.744 356297.699,172961.98 356296.763,172961.882 356291.79,172961.363</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567392" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb5000005200001357" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005200001351"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021730446">
      <osgb:version>4</osgb:version>
      <osgb:versionDate>2017-03-30</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>32.63</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356344.0,172995.0 356341.0,172993.0 356316.809,172976.957</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567393" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567392" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279384655"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005124913028"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005200001351"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021621263">
      <osgb:version>9</osgb:version>
      <osgb:versionDate>2017-04-06</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>A Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>485.5</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356524.0,173105.0 356528.0,173091.0 356529.335,173084.102 356531.0,173074.0 356531.444,173072.379 356531.8,173070.0 356535.0,173054.0 356537.0,173015.0 356536.0,173000.0 356536.0,172968.0 356537.0,172949.0 356545.0,172906.0 356562.0,172829.0 356572.0,172803.0 356600.0,172742.692 356624.0,172691.0 356645.0,172641.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567394" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021562240" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396525"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005109384967"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279381963"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021761944">
      <osgb:version>5</osgb:version>
      <osgb:versionDate>2017-03-02</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Dual Carriageway</osgb:natureOfRoad>
      <osgb:length>30.46</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356291.79,172961.363 356294.714,172965.419 356295.354,172966.306 356307.624,172974.741 356308.0,172975.0 356316.809,172976.957</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb5000005200001357" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567392" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb5000005200001351"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb5000005222316277">
      <osgb:version>1</osgb:version>
      <osgb:versionDate>2018-02-12</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>62.17</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356370.0,173010.0 356372.264,173011.363 356377.375,173014.442 356380.208,173016.104 356422.998,173042.5</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb4000000021567391" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb5000005222316276" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279397345"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396525"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  <osgb:networkMember>
    <osgb:RoadLink fid="osgb4000000021652549">
      <osgb:version>8</osgb:version>
      <osgb:versionDate>2018-02-12</osgb:versionDate>
      <osgb:theme>Road Network</osgb:theme>
      <osgb:descriptiveGroup>Road Topology</osgb:descriptiveGroup>
      <osgb:descriptiveTerm>B Road</osgb:descriptiveTerm>
      <osgb:natureOfRoad>Single Carriageway</osgb:natureOfRoad>
      <osgb:length>118.78</osgb:length>
      <osgb:polyline>
        <gml:LineString srsName="urn:ogc:def:crs:EPSG::27700">
          <gml:coordinates>356422.998,173042.5 356467.578,173070.0 356500.0,173090.0 356524.0,173105.0</gml:coordinates>
        </gml:LineString>
      </osgb:polyline>
      <osgb:directedNode xlink:href="#osgb5000005222316276" orientation="-"/>
      <osgb:directedNode xlink:href="#osgb4000000021567394" gradeSeparation="1" orientation="+"/>
      <osgb:referenceToTopographicArea xlink:href="#osgb1000000279396525"/>
    </osgb:RoadLink>
  </osgb:networkMember>
  </osgb:FeatureCollection>